version: '3.7'

networks:
  api-network:
    external: true
    driver: bridge

services:
  api-fundos-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PARTITIONS=0,1,2,3,4
      - LOG_INFO_PATH=logs/api-fundos-info-1.log
      - LOG_ERROR_PATH=logs/api-fundos-error-1.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
      
  api-fundos-2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PARTITIONS=5,6,7,8,9
      - LOG_INFO_PATH=logs/api-fundos-info-2.log
      - LOG_ERROR_PATH=logs/api-fundos-error-2.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
    
  api-fundos-3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    environment:
      - PARTITIONS=10,11,12,13,14
      - LOG_INFO_PATH=logs/api-fundos-info-3.log
      - LOG_ERROR_PATH=logs/api-fundos-error-3.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network 
    
  api-fundos-4:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    environment:
      - PARTITIONS=15,16,17,18,19
      - LOG_INFO_PATH=logs/api-fundos-info-4.log
      - LOG_ERROR_PATH=logs/api-fundos-error-4.log
    volumes:
      - ./storage:/app/storage
      - ./logs:/app/logs
    networks: 
      - api-network
